### PR TITLE
add OWNERS file to the repository

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Mainly required for prow.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]
Thanks @agarwal-mudit :+1:

**Comment by nixpanic** [comment]
The openshift-cherrypick-robot created a [new repository](https://github.com/openshift-cherrypick-robot/volume-replication-operator) where cherry-pick PRs will be stored.

I won't have permissions to do the cherry-pick, I guess, but lets try anyway.

/cherry-pick release-4.9

**Pull request merged**
